name: base

info:
  description: base environment

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipykernel
  - mamba
  - boa
  - conda-build
  - twine
  - grayskull
  - anaconda-client
