require("sunao.plugins-setup")
require("sunao.core.options")
require("sunao.core.keymaps")
require("sunao.core.colorscheme")
require("sunao.plugins.comment")
require("sunao.plugins.nvim-tree")
require("sunao.plugins.lualine")
require("sunao.plugins.telescope")
require("sunao.plugins.nvim-cmp")
-- require("sunao.plugins.lsp.mason")
-- require("sunao.plugins.lsp.lspsaga")
-- require("sunao.plugins.lsp.lspconfig")
-- require("sunao.plugins.lsp.null-ls")
-- require("sunao.plugins.vimtex")
-- require("sunao.plugins.markdown")
-- require("sunao.plugins.bufferline")
